
-- Seed data for Asava & Arishta
INSERT INTO public.products (name, slug, dosage_form, therapeutic_categories, description, benefits, image_url)
VALUES
  ('Abhayarishta', 'abhayarishta', 'Asava & Arishta', ARRAY['Digestion & Gut'], 'Effective for constipation and piles.', ARRAY['Relieves constipation', 'Treats piles'], NULL),
  ('Ahiphenasava', 'ahiphenasava', 'Asava & Arishta', ARRAY['Digestion & Gut'], 'Used for severe diarrhea and dysentery.', ARRAY['Anti-diarrheal'], NULL),
  ('Amritarishta', 'amritarishta', 'Asava & Arishta', ARRAY['Immunity', 'General Wellness'], 'Immunity booster and fever management.', ARRAY['Boosts immunity', 'Reduces fever'], NULL),
  ('Angoorasava', 'angoorasava', 'Asava & Arishta', ARRAY['General Wellness'], 'Restorative tonic for strength.', ARRAY['Restores strength'], NULL),
  ('Aragwadharishtam', 'aragwadharishtam', 'Asava & Arishta', ARRAY['Skin Health'], 'Blood purifier and skin remedy.', ARRAY['Treats skin diseases'], NULL),
  ('Arjunarishta', 'arjunarishta', 'Asava & Arishta', ARRAY['Heart Care'], 'Cardiac tonic for heart health.', ARRAY['Strengthens heart', 'Regulates BP'], NULL),
  ('Arvindasava', 'arvindasava', 'Asava & Arishta', ARRAY['Kids Health'], 'Paediatric tonic for digestive and general health.', ARRAY['Improves digestion in kids'], NULL),
  ('Ashokarishta', 'ashokarishta', 'Asava & Arishta', ARRAY['Female Health'], 'Uterine tonic for menstrual health.', ARRAY['Regulates periods', 'Reduces pain'], NULL),
  ('Ashwagandharishta', 'ashwagandharishta', 'Asava & Arishta', ARRAY['Mental Health', 'General Wellness'], 'Tonic for vitality and stress.', ARRAY['Reduces stress', 'Improves vitality'], NULL),
  ('Ayaskriti', 'ayaskriti', 'Asava & Arishta', ARRAY['Weight Management', 'Blood Disorders'], 'Used for anemia and obesity.', ARRAY['Treats anemia', 'Aids weight loss'], NULL),
  ('Babularishta', 'babularishta', 'Asava & Arishta', ARRAY['Respiratory Health'], 'Detailed description coming soon.', ARRAY[]::text[], NULL),
  ('Balamritam', 'balamritam', 'Asava & Arishta', ARRAY['Kids Health'], 'Immunity and strength booster for children.', ARRAY['Boosts immunity', 'Promotes growth'], NULL),
  ('Balarishtam', 'balarishtam', 'Asava & Arishta', ARRAY['Bone, Muscle & Joint'], 'Neurological and rheumatic disorders.', ARRAY['Strengthens nerves', 'Relieves joint pain'], NULL),
  ('Bhringrajasava', 'bhringrajasava', 'Asava & Arishta', ARRAY['General Wellness'], 'Rejuvenative tonic.', ARRAY['Improves vitality'], NULL),
  ('Bilvasava', 'bilvasava', 'Asava & Arishta', ARRAY['Digestion & Gut'], 'Treats digestive disorders.', ARRAY['Improves digestion'], NULL),
  ('Chandanasava', 'chandanasava', 'Asava & Arishta', ARRAY['Kidney Health'], 'Cooling tonic for urinary tract.', ARRAY['Treats UTI', 'Cooling effect'], NULL),
  ('Chavikasavam', 'chavikasavam', 'Asava & Arishta', ARRAY['Digestion & Gut'], 'Digestive stimulant.', ARRAY['Improves appetite'], NULL),
  ('Dantyarishta', 'dantyarishta', 'Asava & Arishta', ARRAY['Digestion & Gut'], 'Purgative and digestive.', ARRAY['Relieves constipation'], NULL),
  ('Dasamoolarishtam', 'dasamoolarishtam', 'Asava & Arishta', ARRAY['General Wellness', 'Bone, Muscle & Joint'], 'Restorative tonic for postpartum and general weakness.', ARRAY['Postpartum care', 'Relieves pain'], NULL),
  ('Dashamoola Jeerakam', 'dashamoola-jeerakam', 'Asava & Arishta', ARRAY['Female Health', 'Digestion & Gut'], 'Postnatal care formulation.', ARRAY['Improves digestion', 'Postpartum recovery'], NULL),
  ('Devadarvarishta', 'devadarvarishta', 'Asava & Arishta', ARRAY['Digestion & Gut'], 'Digestive and carminative.', ARRAY['Relieves bloating'], NULL),
  ('Dhatryasava', 'dhatryasava', 'Asava & Arishta', ARRAY['General Wellness'], 'Rejuvenative tonic rich in Vitamin C.', ARRAY['Boosts immunity'], NULL),
  ('Draksharishta', 'draksharishta', 'Asava & Arishta', ARRAY['Digestion & Gut', 'General Wellness'], 'Tonic for General Debility & Improves Digestion', ARRAY['Improves digestion', 'Relieves fatigue'], NULL),
  ('Drakshasava', 'drakshasava', 'Asava & Arishta', ARRAY['General Wellness'], 'Restores Strength after Chronic Disease', ARRAY['Restores strength'], NULL),
  ('Jeerakarishtam', 'jeerakarishtam', 'Asava & Arishta', ARRAY['Female Health', 'Digestion & Gut'], 'For Abdominal and Postpartum Disorders', ARRAY['Postpartum care', 'Digestive health'], NULL),
  ('Kalmeghasava', 'kalmeghasava', 'Asava & Arishta', ARRAY['Liver Health'], 'Best Ayurvedic Medicine for Liver & Spleen Enlargement', ARRAY['Liver tonic', 'Spleen health'], NULL),
  ('Kanakasava', 'kanakasava', 'Asava & Arishta', ARRAY['Cold & Cough'], 'Drug of Choice for Asthma, Biliary and Renal Colic', ARRAY['Relieves asthma', 'Treats colic'], NULL),
  ('Karpoorasava', 'karpoorasava', 'Asava & Arishta', ARRAY['Digestion & Gut'], 'Amazing results in Cholera & Abdominal Muscle Cramps', ARRAY['Relieves cramps', 'Treats diarrhea'], NULL),
  ('Khadirarishta', 'khadirarishta', 'Asava & Arishta', ARRAY['Skin Health'], 'Detoxifies Blood, Skin & Intestine', ARRAY['Purifies blood', 'Treats skin issues'], NULL),
  ('Kumaryasava', 'kumaryasava', 'Asava & Arishta', ARRAY['Liver Health', 'Female Health'], 'Best Medicine for Liver & Menstrual Disorders', ARRAY['Liver health', 'Menstrual regulator'], NULL),
  ('Kushmandasava', 'kushmandasava', 'Asava & Arishta', ARRAY['Blood Disorders'], 'Best Asava for Hemoptysis and Hemorrhagic Disorders', ARRAY['Stops bleeding'], NULL),
  ('Kutajarishta', 'kutajarishta', 'Asava & Arishta', ARRAY['Digestion & Gut'], 'Benefits & Uses in Diarrhea, Dysentery and Amoebiasis', ARRAY['Treats diarrhea', 'Anti-dysenteric'], NULL),
  ('Lodhrasavam', 'lodhrasavam', 'Asava & Arishta', ARRAY['Female Health'], 'For uterine health and skin issues.', ARRAY['Uterine tonic', 'Skin health'], NULL),
  ('Lohasava', 'lohasava', 'Asava & Arishta', ARRAY['Blood Disorders', 'Weight Management'], 'Iron tonic for anemia and obesity.', ARRAY['Treats anemia', 'Aids weight loss'], NULL),
  ('Mrigamadasava', 'mrigamadasava', 'Asava & Arishta', ARRAY['Heart Care'], 'Cardiac stimulant.', ARRAY['Strengthens heart'], NULL),
  ('Mrit Sanjeevani Sura', 'mrit-sanjeevani-sura', 'Asava & Arishta', ARRAY['General Wellness'], 'Revitalizing tonic.', ARRAY['Restores vitality'], NULL),
  ('Mustakarishta', 'mustakarishta', 'Asava & Arishta', ARRAY['Digestion & Gut'], 'Digestive and carminative.', ARRAY['Improves digestion'], NULL),
  ('Palashpushpasava', 'palashpushpasava', 'Asava & Arishta', ARRAY['Kidney Health'], 'For kidney health.', ARRAY['Kidney support'], NULL),
  ('Patrangasava', 'patrangasava', 'Asava & Arishta', ARRAY['Female Health'], 'Uterine tonic.', ARRAY['Menstrual health'], NULL),
  ('Pippalyasavam', 'pippalyasavam', 'Asava & Arishta', ARRAY['Digestion & Gut', 'Cold & Cough'], 'Digestive and respiratory health.', ARRAY['Improves appetite', 'Respiratory support'], NULL),
  ('Punarnavarishta', 'punarnavarishta', 'Asava & Arishta', ARRAY['Kidney Health', 'Liver Health'], 'Diuretic and kidney tonic.', ARRAY['Kidney health', 'Reduces swelling'], NULL),
  ('Punarnavasavam', 'punarnavasavam', 'Asava & Arishta', ARRAY['Kidney Health'], 'Similar to Punarnavarishta.', ARRAY['Kidney support'], NULL),
  ('Raktshodhakarishta', 'raktshodhakarishta', 'Asava & Arishta', ARRAY['Skin Health', 'Blood Disorders'], 'Blood purifier.', ARRAY['Purifies blood', 'Clear skin'], NULL),
  ('Rohitakarishta', 'rohitakarishta', 'Asava & Arishta', ARRAY['Liver Health'], 'For spleen and liver disorders.', ARRAY['Liver support', 'Spleen health'], NULL),
  ('Saraswatarishta', 'saraswatarishta', 'Asava & Arishta', ARRAY['Mental Health', 'Immunity'], 'Excellent Tonic for Memory & Immunity Booster', ARRAY['Boosts memory', 'Improves immunity'], NULL),
  ('Saribadyasavam', 'saribadyasavam', 'Asava & Arishta', ARRAY['Blood Disorders', 'Skin Health'], 'Blood purifier and coolant.', ARRAY['Purifies blood'], NULL),
  ('Takrarishta', 'takrarishta', 'Asava & Arishta', ARRAY['Digestion & Gut'], 'Ayurvedic Fermented Buttermilk Formulation', ARRAY['Improves digestion', 'Treats piles'], NULL),
  ('Ushirasava', 'ushirasava', 'Asava & Arishta', ARRAY['Blood Disorders', 'Skin Health'], 'Hemostatic and cooling.', ARRAY['Stops bleeding', 'Cooling'], NULL),
  ('Vasarishta', 'vasarishta', 'Asava & Arishta', ARRAY['Cold & Cough'], 'Respiratory tonic.', ARRAY['Relieves cough', 'Bronchodilator'], NULL),
  ('Vasasava', 'vasasava', 'Asava & Arishta', ARRAY['Cold & Cough'], 'Respiratory tonic.', ARRAY['Relieves cough'], NULL),
  ('Vidangarishta', 'vidangarishta', 'Asava & Arishta', ARRAY['Digestion & Gut'], 'Anthelmintic (deworming).', ARRAY['Expels worms'], NULL)
ON CONFLICT (slug) DO UPDATE 
SET 
  dosage_form = EXCLUDED.dosage_form,
  therapeutic_categories = EXCLUDED.therapeutic_categories,
  description = EXCLUDED.description,
  benefits = EXCLUDED.benefits;
